version: '2'
services:
  rdb:
    image: rethinkdb
    ports:
      - "9090:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - ./nodes/rdb/data:/data

  api:
    build: nodes/api/
    environment:
      - PORT=$API_PORT_1
    ports:
      - $API_PORT_1

  links:
    build: nodes/links/
    environment:
      - PORT=$API_PORT_2
    ports:
      - $API_PORT_2
    links:
      - rdb

  ui:
    build: 
      context: nodes/ui/
      args:
      - API_HOST=$API_HOST
      - API_PORT=$API_PORT_1
    ports:
      - "$UI_PORT:$UI_PORT"

  lb1:
    image: dockercloud/haproxy
    ports:
      - "$API_PORT_1:80"
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lb2:
    image: dockercloud/haproxy
    ports:
      - "$API_PORT_2:80"
    links:
      - links
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock